# Generated by Django 3.2.3 on 2021-05-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_item_item_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_updated',
        ),
        migrations.AddField(
            model_name='item',
            name='item_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
