# Generated by Django 3.2.3 on 2021-06-10 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210610_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_update',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 10, 17, 57, 8, 718111), null=True, verbose_name='Last Updated'),
        ),
    ]
