# Generated by Django 3.2.3 on 2021-06-10 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_item_item_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_slug',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_update',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 10, 18, 2, 3, 776083), null=True, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='itemseries',
            name='item_series',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
