# Generated by Django 3.2.3 on 2021-06-10 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210610_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_update',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 10, 18, 14, 52, 13604), null=True, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='itemseries',
            name='item_series',
            field=models.CharField(blank=True, default=1, max_length=200, null=True),
        ),
    ]
