# Generated by Django 3.2.3 on 2021-06-10 12:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210610_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_series',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.itemseries', verbose_name='Series'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_update',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 10, 18, 15, 31, 498699), null=True, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='itemseries',
            name='item_series',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
