# Generated by Django 3.2.3 on 2021-06-10 13:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_item_item_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.itemseries', verbose_name='Series'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_update',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 10, 18, 31, 55, 36950), null=True, verbose_name='Last Updated'),
        ),
    ]
