# Generated by Django 3.2.3 on 2021-06-10 13:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210610_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.itemseries', verbose_name='Series'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_update',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 10, 18, 37, 14, 291996), null=True, verbose_name='Last Updated'),
        ),
    ]
