# Generated by Django 3.2.3 on 2021-06-10 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210610_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_update',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 10, 18, 42, 25, 256377), null=True, verbose_name='Last Updated'),
        ),
    ]
