# Generated by Django 3.2.3 on 2021-06-16 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20210616_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_img',
            field=models.ImageField(blank=True, null=True, upload_to='item_image/<django.db.models.fields.CharField>.jpg'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_update',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 16, 19, 8, 38, 992442), null=True, verbose_name='Last Updated'),
        ),
    ]
