# Generated by Django 3.2.3 on 2021-06-16 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20210616_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_update',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 16, 19, 17, 56, 698761), null=True, verbose_name='Last Updated'),
        ),
    ]
