# Generated by Django 3.2.3 on 2021-07-16 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_item_item_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_update',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 16, 12, 31, 45, 217793), null=True, verbose_name='Last Updated'),
        ),
    ]
